about:
    home: 'https://github.com/BenLangmead/bowtie'
    license: Artistic
    summary: An ultrafast memory-efficient short read aligner

package:
    name: bowtie
    version: 1.2.0

build:
  number: 0
  skip: False

requirements:
    build:
        - python
        - gcc [not osx]
        - llvm [osx]
        - tbb
    run:
        - libgcc [not osx]
        - python
        - tbb


test:
    commands:
        - (bowtie --version 2>&1) > /dev/null

source:
  fn: bowtie-1.2.0.tar.gz
  url: https://github.com/BenLangmead/bowtie/archive/v1.2.0.tar.gz
  sha256: dc4e7951b8eca56ce7714c47fd4e84f72badd5312ee9546c912af1963570f894
