about:
  home: 'http://bowtie-bio.sourceforge.net/bowtie2/index.shtml'
  license: GPLv3
  summary: Fast and sensitive read alignment

package:
  name: bowtie2
  version: 2.3.0

source:
  fn: bowtie2-2.3.0-source.zip # [linux]
  url: https://downloads.sourceforge.net/project/bowtie-bio/bowtie2/2.3.0/bowtie2-2.3.0-source.zip # [linux]
  sha256: edd4c061fae8e0087dac606bd8d37299371a25dc1fb6eee28eec445f9918fce5 # [linux]
  fn: bowtie2-2.3.0-macos-x86_64.zip # [osx]
  url: https://downloads.sourceforge.net/project/bowtie-bio/bowtie2/2.3.0/bowtie2-2.3.0-macos-x86_64.zip # [osx]
  sha256: e614f516be03d843ec9fc4f44b1b9e501342c7f1b9af41eb80c4df22058ed766 # [osx]

build:
  number: 0

requirements:
  build:
    - gcc   # [linux]
    - python
  run:
    - python
    - perl-threaded
    - libgcc    # [linux]

test:
  commands:
    - bowtie2 --version
    - bowtie2-build --help
    - bowtie2-inspect-l --help
    - bowtie2-align-s --help
